return {
    id = "329_MT_arc_weapon_teamGlow",
    -- shader = "Shader Graphs/Ship Glow Shader",
    -- keywords = { "_EMISSION" },
    -- properties = {
    --     _CloakOpacity = 1,
    --     _Color = { 0.3, 0.3, 0.3, .1 },
    --     _DamageEnd = 0,
    --     _DamageStart = 0.8,
    --     _Dead = 0,
    --     _DitherScale = 1,
    --     _EmissionColor = { 0.3, 1.5, 1.5, 1 },
    --     _Intensity = 1,
    --     _Metallic = 0,
    --     _Min = 0.5,
    --     _QueueControl = 0,
    --     _QueueOffset = 0,
    --     _Smoothness = 0,
    --     Damage = 0,
    -- },


    shader = "Universal Render Pipeline/Complex Lit",
    keywords = { "_EMISSION", "_ENVIRONMENTREFLECTIONS_OFF", "_RECEIVE_SHADOWS_OFF", "_SPECULARHIGHLIGHTS_OFF", "_SURFACE_TYPE_TRANSPARENT" },
    renderQueue = 3001,
    properties = {
        _AddPrecomputedVelocity = 0,
        _AlphaClip = 0,
        _AlphaToMask = 0,
        _BaseColor = { .4, 1, 1, 0.5 },
        _Blend = 2,
        _BlendModePreserveSpecular = 0,
        _BlendOp = 0,
        _BumpScale = 1,
        _ClearCoat = 0,
        _ClearCoatMask = 0,
        _ClearCoatSmoothness = 0,
        _Cull = 2,
        _Cutoff = 0.1,
        _DetailAlbedoMapScale = 1,
        _DetailNormalMapScale = 1,
        _DstBlend = 1,
        _DstBlendAlpha = 1,
        _EmissionColor = { .5, 1, 1, 1 },
        _EnvironmentReflections = 0,
        _Metallic = 0,
        _OcclusionStrength = 1,
        _Parallax = 0.02,
        _QueueOffset = 1,
        _ReceiveShadows = 0,
        _Smoothness = 0,
        _SmoothnessTextureChannel = 0,
        _SpecColor = { 0, 0, 0, 0 },
        _SpecularHighlights = 0,
        _SrcBlend = 5,
        _SrcBlendAlpha = 1,
        _Surface = 1,
        _WorkflowMode = 1,
        _XRMotionVectorsPass = 1,
        _ZWrite = 0,
    },
}
