return {
    id = "329_MT_arc_vortex_scan",
    shader = "Shader Graphs/VortexUnlit_SG",
    properties = {
        _Center = { .5, .5, 0, 0 },
        _Color = { 1, 1, 1, 1 },
        _Direction = 1,
        _FadeOuter = .9,
        _FadeSoftness = 0.12,
        _FalloffInner = 0,
        _FalloffOuter = 10,
        _InvRStrength = 0.1,
        _MainTex = { texture = "Textures/gwe_vortex.png" },
        _NoiseSpeed = { 0, .2, 0, 0 },
        _NoiseTiling = { 0, 10, 0, 0 },
        _Opacity = 0.1,
        _QueueControl = 0,
        _QueueOffset = 0,
        _SpinSpeed = 0,
        _Twist = 100,
        Opacity = 1,
    },
}
