return {
    id = "arc_vortex",
    shader = "Shader Graphs/VortexUnlit_SG",
    properties = {
        _Center = { 0.5, 0.5, 0, 0 },
        _Color = { 0.5, 0.5, 0.5, 1 },
        _Direction = 1,
        _FadeOuter = 0.5,
        _FadeSoftness = 0.12,
        _FalloffInner = 0,
        _FalloffOuter = 1,
        _InvRStrength = 0.1,
        _MainTex = { texture = "Textures/noise_vortex.png" },
        _NoiseSpeed = { 0, 0, 0, 0 },
        _NoiseTiling = { 2, 2, 0, 0 },
        _Opacity = 0.32,
        _QueueControl = 0,
        _QueueOffset = 0,
        _SpinSpeed = 0.2,
        _Twist = 3,
        Opacity = 1,
    },
}
