return {
    id = "arc_muzzleFlash_teamGlow",
    shader = "Shader Graphs/Ship Glow Shader",
    keywords = { "_EMISSION" },
    properties = {
        _CloakOpacity = 1,
        _Color = { 0.3, 0.3, 0.3, .5 },
        _DamageEnd = 0,
        _DamageStart = 0.8,
        _Dead = 0,
        _DitherScale = 1,
        _EmissionColor = { 0.3, 1.5, 1.5, 1 },
        _Intensity = 1,
        _Metallic = 0,
        _Min = 0.5,
        _QueueControl = 0,
        _QueueOffset = 0,
        _Smoothness = 0,
        Damage = 0,
    },
}
