return {
    id = "arc_aurora-pink",
    shader = "Shader Graphs/Ship Glow Shader",
    keywords = { "_EMISSION" },
    properties = {
        _CloakOpacity = 1,
        _Color = { 1, .5, .5, 0 },
        _DamageEnd = 0,
        _DamageStart = 0.8,
        _Dead = 0,
        _DitherScale = 1,
        _EmissionColor = { 0.25, 0.125, 0.125, .0},
        _Intensity = 1,
        _Metallic = 0,
        _Min = 0.5,
        _QueueControl = 0,
        _QueueOffset = 0,
        _Smoothness = 0,
        Damage = 0,
    },
}
